schemaVersion: 2.2.0
metadata:
  name: elasticsearch-operator
components:
  - name: tools
    attributes:
       controller.devfile.io/merge-contribution: true
    container:
      image: quay.io/webcenter/developer-image:golang-ubi9-latest
  
