apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bootstrap
    app.kubernetes.io/instance: rolemapping-viewer-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: bootstrap
  name: elastic-operator-rolemapping-viewer-role
rules:
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - rolemappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - rolemappings/status
  verbs:
  - get
