apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bootstrap
    app.kubernetes.io/instance: watch-editor-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: bootstrap
  name: elasticsearch-operator-watch-editor-role
rules:
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - watches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - watches/status
  verbs:
  - get
