apiVersion: kibanaapi.k8s.webcenter.fr/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/created-by: elasticsearch-operator
    app.kubernetes.io/instance: role-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: elasticsearch-operator
  name: role-sample
spec:
  kibana:
  - base:
    - all
    spaces:
    - userspace-sample
  kibanaRef:
    managed:
      name: kibana
