apiVersion: elasticsearchapi.k8s.webcenter.fr/v1alpha1
kind: Role
metadata:
  labels:
    app.kubernetes.io/created-by: bootstrap
    app.kubernetes.io/instance: role-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: bootstrap
  name: role-sample
spec:
  cluster:
  - monitor
  - read_ilm
  - read_slm
  - cluster:admin/slm/status
  - cluster:admin/snapshot/get
  elasticsearchRef:
    managed:
      name: elasticsearch-sample
  indices:
  - names:
    - '*'
    privileges:
    - view_index_metadata
    - monitor
