//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package shared

import (
	"k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchExternalRef) DeepCopyInto(out *ElasticsearchExternalRef) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchExternalRef.
func (in *ElasticsearchExternalRef) DeepCopy() *ElasticsearchExternalRef {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchExternalRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchManagedRef) DeepCopyInto(out *ElasticsearchManagedRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchManagedRef.
func (in *ElasticsearchManagedRef) DeepCopy() *ElasticsearchManagedRef {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchManagedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchRef) DeepCopyInto(out *ElasticsearchRef) {
	*out = *in
	if in.ManagedElasticsearchRef != nil {
		in, out := &in.ManagedElasticsearchRef, &out.ManagedElasticsearchRef
		*out = new(ElasticsearchManagedRef)
		**out = **in
	}
	if in.ExternalElasticsearchRef != nil {
		in, out := &in.ExternalElasticsearchRef, &out.ExternalElasticsearchRef
		*out = new(ElasticsearchExternalRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ElasticsearchCaSecretRef != nil {
		in, out := &in.ElasticsearchCaSecretRef, &out.ElasticsearchCaSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchRef.
func (in *ElasticsearchRef) DeepCopy() *ElasticsearchRef {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricbeatMonitoringSpec) DeepCopyInto(out *MetricbeatMonitoringSpec) {
	*out = *in
	in.ElasticsearchRef.DeepCopyInto(&out.ElasticsearchRef)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricbeatMonitoringSpec.
func (in *MetricbeatMonitoringSpec) DeepCopy() *MetricbeatMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MetricbeatMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}
