apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: elasticsearch-operator
  name: elasticsearch-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: elasticsearch-operator
