# permissions for end users to edit cerebroes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cerebro-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: elasticsearch-operator
    app.kubernetes.io/part-of: elasticsearch-operator
    app.kubernetes.io/managed-by: kustomize
  name: cerebro-editor-role
rules:
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - cerebroes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - cerebroes/status
  verbs:
  - get
