# permissions for end users to view cerebroes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cerebro-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: elasticsearch-operator
    app.kubernetes.io/part-of: elasticsearch-operator
    app.kubernetes.io/managed-by: kustomize
  name: cerebro-viewer-role
rules:
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - cerebroes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - cerebroes/status
  verbs:
  - get
