# permissions for end users to view indexlifecyclepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: indexlifecyclepolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bootstrap
    app.kubernetes.io/part-of: bootstrap
    app.kubernetes.io/managed-by: kustomize
  name: indexlifecyclepolicy-viewer-role
rules:
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indexlifecyclepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indexlifecyclepolicies/status
  verbs:
  - get
