# permissions for end users to edit elasticsearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearch-editor-role
rules:
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches/status
  verbs:
  - get
