# permissions for end users to edit logstashes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: logstash-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bootstrap
    app.kubernetes.io/part-of: bootstrap
    app.kubernetes.io/managed-by: kustomize
  name: logstash-editor-role
rules:
- apiGroups:
  - logstash.k8s.webcenter.fr
  resources:
  - logstashes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logstash.k8s.webcenter.fr
  resources:
  - logstashes/status
  verbs:
  - get
