---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas/status
  verbs:
  - get
  - patch
  - update
