---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indexlifecyclepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indexlifecyclepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indexlifecyclepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - licenses/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - licenses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - rolemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - rolemappings/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - rolemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotlifecyclepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotlifecyclepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotlifecyclepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas/status
  verbs:
  - get
  - patch
  - update
