---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: elastic-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beat.k8s.webcenter.fr
  resources:
  - filebeats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beat.k8s.webcenter.fr
  resources:
  - filebeats/finalizers
  verbs:
  - update
- apiGroups:
  - beat.k8s.webcenter.fr
  resources:
  - filebeats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - beat.k8s.webcenter.fr
  resources:
  - metricbeats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beat.k8s.webcenter.fr
  resources:
  - metricbeats/finalizers
  verbs:
  - update
- apiGroups:
  - beat.k8s.webcenter.fr
  resources:
  - metricbeats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - cerebroes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - cerebroes/finalizers
  verbs:
  - update
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - cerebroes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - hosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - hosts/finalizers
  verbs:
  - update
- apiGroups:
  - cerebro.k8s.webcenter.fr
  resources:
  - hosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearch.k8s.webcenter.fr
  resources:
  - elasticsearches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - componenttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - componenttemplates/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - componenttemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indexlifecyclepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indexlifecyclepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indexlifecyclepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indextemplates/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - indextemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - licenses/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - licenses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - rolemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - rolemappings/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - rolemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotlifecyclepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotlifecyclepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotlifecyclepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - snapshotrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - watches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - watches/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearchapi.k8s.webcenter.fr
  resources:
  - watches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.k8s.webcenter.fr
  resources:
  - kibanas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - logstashpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - logstashpipelines/finalizers
  verbs:
  - update
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - logstashpipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - userspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - userspaces/finalizers
  verbs:
  - update
- apiGroups:
  - kibanaapi.k8s.webcenter.fr
  resources:
  - userspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logstash.k8s.webcenter.fr
  resources:
  - logstashes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logstash.k8s.webcenter.fr
  resources:
  - logstashes/finalizers
  verbs:
  - update
- apiGroups:
  - logstash.k8s.webcenter.fr
  resources:
  - logstashes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
