//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaRoleElasticsearch) DeepCopyInto(out *KibanaRoleElasticsearch) {
	*out = *in
	if in.Indices != nil {
		in, out := &in.Indices, &out.Indices
		*out = make([]KibanaRoleElasticsearchIndice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RunAs != nil {
		in, out := &in.RunAs, &out.RunAs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaRoleElasticsearch.
func (in *KibanaRoleElasticsearch) DeepCopy() *KibanaRoleElasticsearch {
	if in == nil {
		return nil
	}
	out := new(KibanaRoleElasticsearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaRoleElasticsearchIndice) DeepCopyInto(out *KibanaRoleElasticsearchIndice) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaRoleElasticsearchIndice.
func (in *KibanaRoleElasticsearchIndice) DeepCopy() *KibanaRoleElasticsearchIndice {
	if in == nil {
		return nil
	}
	out := new(KibanaRoleElasticsearchIndice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaRoleKibana) DeepCopyInto(out *KibanaRoleKibana) {
	*out = *in
	if in.Base != nil {
		in, out := &in.Base, &out.Base
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Feature != nil {
		in, out := &in.Feature, &out.Feature
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Spaces != nil {
		in, out := &in.Spaces, &out.Spaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaRoleKibana.
func (in *KibanaRoleKibana) DeepCopy() *KibanaRoleKibana {
	if in == nil {
		return nil
	}
	out := new(KibanaRoleKibana)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaRoleTransientMetadata) DeepCopyInto(out *KibanaRoleTransientMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaRoleTransientMetadata.
func (in *KibanaRoleTransientMetadata) DeepCopy() *KibanaRoleTransientMetadata {
	if in == nil {
		return nil
	}
	out := new(KibanaRoleTransientMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaSpaceObjectParameter) DeepCopyInto(out *KibanaSpaceObjectParameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaSpaceObjectParameter.
func (in *KibanaSpaceObjectParameter) DeepCopy() *KibanaSpaceObjectParameter {
	if in == nil {
		return nil
	}
	out := new(KibanaSpaceObjectParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KibanaUserSpaceCopy) DeepCopyInto(out *KibanaUserSpaceCopy) {
	*out = *in
	if in.IncludeReferences != nil {
		in, out := &in.IncludeReferences, &out.IncludeReferences
		*out = new(bool)
		**out = **in
	}
	if in.Overwrite != nil {
		in, out := &in.Overwrite, &out.Overwrite
		*out = new(bool)
		**out = **in
	}
	if in.CreateNewCopies != nil {
		in, out := &in.CreateNewCopies, &out.CreateNewCopies
		*out = new(bool)
		**out = **in
	}
	if in.ForceUpdateWhenReconcile != nil {
		in, out := &in.ForceUpdateWhenReconcile, &out.ForceUpdateWhenReconcile
		*out = new(bool)
		**out = **in
	}
	if in.KibanaObjects != nil {
		in, out := &in.KibanaObjects, &out.KibanaObjects
		*out = make([]KibanaSpaceObjectParameter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KibanaUserSpaceCopy.
func (in *KibanaUserSpaceCopy) DeepCopy() *KibanaUserSpaceCopy {
	if in == nil {
		return nil
	}
	out := new(KibanaUserSpaceCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogstashPipeline) DeepCopyInto(out *LogstashPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogstashPipeline.
func (in *LogstashPipeline) DeepCopy() *LogstashPipeline {
	if in == nil {
		return nil
	}
	out := new(LogstashPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogstashPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogstashPipelineList) DeepCopyInto(out *LogstashPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogstashPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogstashPipelineList.
func (in *LogstashPipelineList) DeepCopy() *LogstashPipelineList {
	if in == nil {
		return nil
	}
	out := new(LogstashPipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogstashPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogstashPipelineSpec) DeepCopyInto(out *LogstashPipelineSpec) {
	*out = *in
	in.KibanaRef.DeepCopyInto(&out.KibanaRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogstashPipelineSpec.
func (in *LogstashPipelineSpec) DeepCopy() *LogstashPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(LogstashPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogstashPipelineStatus) DeepCopyInto(out *LogstashPipelineStatus) {
	*out = *in
	in.BasicRemoteObjectStatus.DeepCopyInto(&out.BasicRemoteObjectStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogstashPipelineStatus.
func (in *LogstashPipelineStatus) DeepCopy() *LogstashPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(LogstashPipelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Role) DeepCopyInto(out *Role) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Role.
func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := new(Role)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Role) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleList) DeepCopyInto(out *RoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Role, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleList.
func (in *RoleList) DeepCopy() *RoleList {
	if in == nil {
		return nil
	}
	out := new(RoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleSpec) DeepCopyInto(out *RoleSpec) {
	*out = *in
	in.KibanaRef.DeepCopyInto(&out.KibanaRef)
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = new(KibanaRoleElasticsearch)
		(*in).DeepCopyInto(*out)
	}
	if in.Kibana != nil {
		in, out := &in.Kibana, &out.Kibana
		*out = make([]KibanaRoleKibana, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransientMedata != nil {
		in, out := &in.TransientMedata, &out.TransientMedata
		*out = new(KibanaRoleTransientMetadata)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleSpec.
func (in *RoleSpec) DeepCopy() *RoleSpec {
	if in == nil {
		return nil
	}
	out := new(RoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleStatus) DeepCopyInto(out *RoleStatus) {
	*out = *in
	in.BasicRemoteObjectStatus.DeepCopyInto(&out.BasicRemoteObjectStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleStatus.
func (in *RoleStatus) DeepCopy() *RoleStatus {
	if in == nil {
		return nil
	}
	out := new(RoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSpace) DeepCopyInto(out *UserSpace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSpace.
func (in *UserSpace) DeepCopy() *UserSpace {
	if in == nil {
		return nil
	}
	out := new(UserSpace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserSpace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSpaceList) DeepCopyInto(out *UserSpaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserSpace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSpaceList.
func (in *UserSpaceList) DeepCopy() *UserSpaceList {
	if in == nil {
		return nil
	}
	out := new(UserSpaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserSpaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSpaceSpec) DeepCopyInto(out *UserSpaceSpec) {
	*out = *in
	in.KibanaRef.DeepCopyInto(&out.KibanaRef)
	if in.DisabledFeatures != nil {
		in, out := &in.DisabledFeatures, &out.DisabledFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KibanaUserSpaceCopies != nil {
		in, out := &in.KibanaUserSpaceCopies, &out.KibanaUserSpaceCopies
		*out = make([]KibanaUserSpaceCopy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSpaceSpec.
func (in *UserSpaceSpec) DeepCopy() *UserSpaceSpec {
	if in == nil {
		return nil
	}
	out := new(UserSpaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSpaceStatus) DeepCopyInto(out *UserSpaceStatus) {
	*out = *in
	in.BasicRemoteObjectStatus.DeepCopyInto(&out.BasicRemoteObjectStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSpaceStatus.
func (in *UserSpaceStatus) DeepCopy() *UserSpaceStatus {
	if in == nil {
		return nil
	}
	out := new(UserSpaceStatus)
	in.DeepCopyInto(out)
	return out
}
