apiVersion: elasticsearchapi.k8s.webcenter.fr/v1alpha1
kind: SnapshotLifecyclePolicy
metadata:
  labels:
    app.kubernetes.io/name: snapshotlifecyclepolicy
    app.kubernetes.io/instance: snapshotlifecyclepolicy-sample
    app.kubernetes.io/part-of: bootstrap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bootstrap
  name: snapshotlifecyclepolicy-sample
spec:
  # TODO(user): Add fields here
