apiVersion: elasticsearchapi.k8s.webcenter.fr/v1
kind: SnapshotLifecyclePolicy
metadata:
  labels:
    app.kubernetes.io/name: snapshotlifecyclepolicy
    app.kubernetes.io/instance: snapshotlifecyclepolicy-sample
    app.kubernetes.io/part-of: bootstrap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bootstrap
  name: snapshotlifecyclepolicy-sample
spec:
  elasticsearchRef:
    managed:
      name: elasticsearch-sample
  schedule: '0 30 1 * * ?'
  name: '<daily-snap-{now/d}>'
  repository: 'snapshot'
  config:
    indices:
      - '.kibana_*'
    ignoreUnavailable: false
    includeGlobalState: false
  retention:
    expireAfter: '7d'
    maxCount: 10
    minCount: 5
