apiVersion: elasticsearchapi.k8s.webcenter.fr/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: role-sample
    app.kubernetes.io/part-of: bootstrap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bootstrap
  name: role-sample
spec:
  elasticsearchRef:
    managed:
      name: elasticsearch-sample
  cluster:
    - 'monitor'
    - 'read_ilm'
    - 'read_slm'
    - 'cluster:admin/slm/status'
    - 'cluster:admin/snapshot/get'
  indices:
    - names: 
        - '*'
      privileges:
        - 'view_index_metadata'
        - 'monitor'
