apiVersion: elasticsearch.k8s.webcenter.fr/v1
kind: Elasticsearch
metadata:
  name: sample
  labels:
    env: test
spec:
  version: 8.6.0
  setVMMaxMapCount: false
  tls:
    enabled: true
    validityDays: 360
    renewalDays: 60
    keySize: 2048
  endpoint:
    ingress:
      enabled: true
      host: elasticsearch.cluster.local
      secretRef:
        name: es-tls
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 512M
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  globalNodeGroup:
    antiAffinity:
      type: soft
      topologyKey: 'topology.kubernetes.io/zone'
    initContainerResources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "25m"
        memory: "64Mi"
    config:
      action.destructive_requires_name: true
      cluster.routing.allocation.disk.watermark.flood_stage: 1gb
      cluster.routing.allocation.disk.watermark.high: 1gb
      cluster.routing.allocation.disk.watermark.low: 2gb
      
      gateway.expected_data_nodes: 1
      gateway.recover_after_data_nodes: 1
      gateway.recover_after_time: 5m
      http.cors.allow-credentials: true
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization
      http.cors.allow-origin: /.*/
      http.cors.enabled: true
      http.max_content_length: 500mb
      
      # Rack awarness
      cluster.routing.allocation.awareness.attributes: node_name
      
      xpack.security.audit.enabled: true
      xpack.security.audit.logfile.events.exclude:
        - access_granted
      xpack.security.authc:
        anonymous:
          authz_exception: false
          roles: monitoring
          username: anonymous_user
  nodeGroups:
    - name: all
      replicas: 1
      roles:
        - master
        - data_hot
        - data_content
        - ingest
      resources:
        requests:
          cpu: "250m"
          memory: "2Gi"
        limits:
          cpu: "1000m"
          memory: "2Gi"