apiVersion: elasticsearchapi.k8s.webcenter.fr/v1alpha1
kind: RoleMapping
metadata:
  labels:
    app.kubernetes.io/name: rolemapping
    app.kubernetes.io/instance: rolemapping-sample
    app.kubernetes.io/part-of: bootstrap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bootstrap
  name: rolemapping-sample
spec:
  # TODO(user): Add fields here
