apiVersion: elasticsearchapi.k8s.webcenter.fr/v1alpha1
kind: Watch
metadata:
  labels:
    app.kubernetes.io/name: watch
    app.kubernetes.io/instance: watch-sample
    app.kubernetes.io/part-of: bootstrap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bootstrap
  name: watch-sample
spec:
  # TODO(user): Add fields here
