apiVersion: kibanaapi.k8s.webcenter.fr/v1alpha1
kind: LogstashPipeline
metadata:
  labels:
    app.kubernetes.io/name: logstashpipeline
    app.kubernetes.io/instance: logstashpipeline-sample
    app.kubernetes.io/part-of: elasticsearch-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: elasticsearch-operator
  name: logstashpipeline-sample
spec:
  # TODO(user): Add fields here
