apiVersion: kibana.k8s.webcenter.fr/v1alpha1
kind: Kibana
metadata:
  labels:
    env: test
  name: sample
spec:
  version: 8.6.0
  elasticsearchRef:
    managed:
      name: elasticsearch-sample
  monitoring:
    prometheus:
      enabled: true
  tls:
    enabled: true
    validityDays: 360
    renewalDays: 60
    keySize: 2048
  endpoint:
    ingress:
      enabled: true
      host: kibana.cluster.local
      secretRef:
        name: kb-tls
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  keystoreSecretRef:
    name: kb-keystore
  config:
    kibana.yml: |
      elasticsearch.requestTimeout: 300000
      unifiedSearch.autocomplete.valueSuggestions.timeout: 3000
      xpack.reporting.roles.enabled: false
  deployment:
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "250m"
        memory: "512Mi"
    node: '--max-old-space-size=2048'
    initContainerResources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "25m"
        memory: "64Mi"
    podTemplate:
      metadata:
        annotations:
          co.elastic.logs.kibana/multiline.pattern: '^\{'
          co.elastic.logs.kibana/multiline.negate: 'true'
          co.elastic.logs.kibana/multiline.match: 'after'
          co.elastic.logs.kibana/multiline.timeout: '5s'
          co.elastic.logs.kibana/processors.0.decode_json_fields: '{"fields": ["message"], "target": "hm.kibana", "add_error_key": true, "max_depth": 10}'
          co.elastic.logs.kibana/processors.2.add_fields: '{"target": "", "fields": {"event": {"dataset": "kibana"}, "service": {"type": "kibana"}}}'
      spec:
        containers: []