apiVersion: logstash.k8s.webcenter.fr/v1alpha1
kind: Logstash
metadata:
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/instance: logstash-sample
    app.kubernetes.io/part-of: bootstrap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bootstrap
  name: logstash-sample
spec:
  # TODO(user): Add fields here
