package kafka

import (
	strimzicrd "github.com/RedHatInsights/strimzi-client-go/apis/kafka.strimzi.io/v1beta2"
	discovercrd "github.com/webcenter-fr/elasticsearch-operator/api/discover/v1"
	"github.com/webcenter-fr/elasticsearch-operator/internal/controller/discover"
)

// GetSecretNameForFile permit to get secret name for file
func GetSecretNameForFile(kk *discovercrd.Kafka) string {
	return discover.GetSecretNameForFile(kk.Name, kk.Spec.TargetSecretFileRef)
}

// GetSecretNameForEnv permit to get secret name for env
func GetSecretNameForEnv(kk *discovercrd.Kafka) string {
	return discover.GetSecretNameForEnv(kk.Name, kk.Spec.TargetSecretEnvRef)
}

// getLabels permit to return global label must be set on all resources
func getLabels(kk *discovercrd.Kafka, customLabels ...map[string]string) (labels map[string]string) {
	return discover.GetLabels(discovercrd.KafkaAnnotationKey, kk.Name, kk.Labels, customLabels...)
}

// getAnnotations permit to return global annotations must be set on all resources
func getAnnotations(kk *discovercrd.Kafka, customAnnotations ...map[string]string) (annotations map[string]string) {
	return discover.GetAnnotations(discovercrd.KafkaAnnotationKey, kk.GetInternalName(), customAnnotations...)
}

// getEnvSuffix permit to return env suffix from Kafka name
func getEnvSuffix(kk *discovercrd.Kafka) string {
	return discover.GetEnvSuffix(kk.GetInternalName())
}

// kafkaHaveClusterCa permit to know if Kafka cluster CA is generated by Strimzi
func kafkaHaveClusterCa(kk *strimzicrd.Kafka) bool {
	return kk.Spec.ClusterCa == nil || kk.Spec.ClusterCa.GenerateCertificateAuthority == nil || *kk.Spec.ClusterCa.GenerateCertificateAuthority
}
