package kafka

import (
	strimzicrd "github.com/RedHatInsights/strimzi-client-go/apis/kafka.strimzi.io/v1beta2"
	discovercrd "github.com/webcenter-fr/elasticsearch-operator/api/discover/v1"
	"github.com/webcenter-fr/elasticsearch-operator/internal/controller/discover"
)

// GetSecretNameForFile permit to get secret name for file
func GetSecretNameForFile(kk *discovercrd.Kafka) string {
	return discover.GetSecretNameForFile(kk.Name, kk.Spec.TargetSecretFileRef)
}

// GetSecretNameForEnv permit to get secret name for env
func GetSecretNameForEnv(kk *discovercrd.Kafka) string {
	return discover.GetSecretNameForEnv(kk.Name, kk.Spec.TargetSecretEnvRef)
}

// getLabels permit to return global label must be set on all resources
func getLabels(kk *discovercrd.Kafka, customLabels ...map[string]string) (labels map[string]string) {
	return discover.GetLabels(discovercrd.KafkaAnnotationKey, kk.Name, kk.Labels, customLabels...)
}

// getAnnotations permit to return global annotations must be set on all resources
func getAnnotations(kk *discovercrd.Kafka, customAnnotations ...map[string]string) (annotations map[string]string) {
	return discover.GetAnnotations(discovercrd.KafkaAnnotationKey, kk.GetInternalName(), customAnnotations...)
}

// getEnvSuffix permit to return env suffix from Kafka name
func getEnvSuffix(kk *discovercrd.Kafka) string {
	return discover.GetEnvSuffix(kk.GetInternalName())
}

// kafkaHaveClusterCa permit to know if Kafka cluster CA is generated by Strimzi
func kafkaHaveClusterCa(kk *strimzicrd.Kafka) bool {
	if kk == nil || kk.Spec == nil {
		return false
	}
	return kk.Spec.ClusterCa == nil || kk.Spec.ClusterCa.GenerateCertificateAuthority == nil || *kk.Spec.ClusterCa.GenerateCertificateAuthority
}

// getSpecListener permit to find the Kafka spec listener that matches the status
// listener name. When the name is not available, it falls back to the given
// index. It returns nil when no listener matches.
func getSpecListener(kk *strimzicrd.Kafka, listenerName string, index int) *strimzicrd.KafkaSpecKafkaListenersElem {
	if kk == nil || kk.Spec == nil {
		return nil
	}

	if listenerName != "" {
		for i := range kk.Spec.Kafka.Listeners {
			listener := &kk.Spec.Kafka.Listeners[i]
			if listener.Name != "" && listener.Name == listenerName {
				return listener
			}
		}
	}

	if index >= 0 && index < len(kk.Spec.Kafka.Listeners) {
		return &kk.Spec.Kafka.Listeners[index]
	}

	return nil
}

// getListenerAuthentication permit to get the authentication configuration of the
// spec listener that matches the given status listener
func getListenerAuthentication(kk *strimzicrd.Kafka, listener strimzicrd.KafkaStatusListenersElem, index int) *strimzicrd.KafkaSpecKafkaListenersElemAuthentication {
	listenerName := ""
	if listener.Name != nil {
		listenerName = *listener.Name
	}

	specListener := getSpecListener(kk, listenerName, index)
	if specListener == nil {
		return nil
	}

	return specListener.Authentication
}
