# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/elasticsearch.k8s.webcenter.fr_elasticsearches.yaml
- bases/kibana.k8s.webcenter.fr_kibanas.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_users.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_licenses.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_roles.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_rolemappings.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_indexlifecyclepolicies.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_snapshotlifecyclepolicies.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_snapshotrepositories.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_indextemplates.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_componenttemplates.yaml
- bases/elasticsearchapi.k8s.webcenter.fr_watches.yaml
- bases/logstash.k8s.webcenter.fr_logstashes.yaml
- bases/beat.k8s.webcenter.fr_filebeats.yaml
- bases/beat.k8s.webcenter.fr_metricbeats.yaml
- bases/cerebro.k8s.webcenter.fr_cerebroes.yaml
- bases/cerebro.k8s.webcenter.fr_hosts.yaml
- bases/kibanaapi.k8s.webcenter.fr_userspaces.yaml
- bases/kibanaapi.k8s.webcenter.fr_roles.yaml
- bases/kibanaapi.k8s.webcenter.fr_logstashpipelines.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_elasticsearches.yaml
#- patches/webhook_in_kibanas.yaml
#- patches/webhook_in_users.yaml
#- patches/webhook_in_licenses.yaml
#- patches/webhook_in_roles.yaml
#- patches/webhook_in_rolemappings.yaml
#- patches/webhook_in_indexlifecyclepolicies.yaml
#- patches/webhook_in_snapshotlifecyclepolicies.yaml
#- patches/webhook_in_snapshotrepositories.yaml
#- patches/webhook_in_indextemplates.yaml
#- patches/webhook_in_componenttemplates.yaml
#- patches/webhook_in_watches.yaml
#- patches/webhook_in_logstashes.yaml
#- patches/webhook_in_filebeats.yaml
#- patches/webhook_in_metricbeats.yaml
#- patches/webhook_in_cerebroes.yaml
#- patches/webhook_in_hosts.yaml
#- patches/webhook_in_userspaces.yaml
#- patches/webhook_in_logstashpipelines.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_elasticsearches.yaml
#- patches/cainjection_in_kibanas.yaml
#- patches/cainjection_in_users.yaml
#- patches/cainjection_in_licenses.yaml
#- patches/cainjection_in_roles.yaml
#- patches/cainjection_in_rolemappings.yaml
#- patches/cainjection_in_indexlifecyclepolicies.yaml
#- patches/cainjection_in_snapshotlifecyclepolicies.yaml
#- patches/cainjection_in_snapshotrepositories.yaml
#- patches/cainjection_in_indextemplates.yaml
#- patches/cainjection_in_componenttemplates.yaml
#- patches/cainjection_in_watches.yaml
#- patches/cainjection_in_logstashes.yaml
#- patches/cainjection_in_filebeats.yaml
#- patches/cainjection_in_metricbeats.yaml
#- patches/cainjection_in_cerebroes.yaml
#- patches/cainjection_in_hosts.yaml
#- patches/cainjection_in_userspaces.yaml
#- patches/cainjection_in_logstashpipelines.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patches/filebeat-patches.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: filebeats.beat.k8s.webcenter.fr
    version: v1
- path: patches/metricbeat-patches.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: metricbeats.beat.k8s.webcenter.fr
    version: v1
- path: patches/cerebro-patches.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: cerebroes.cerebro.k8s.webcenter.fr
    version: v1
- path: patches/elasticsearch-patches.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: elasticsearches.elasticsearch.k8s.webcenter.fr
    version: v1
- path: patches/kibana-patches.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: kibanas.kibana.k8s.webcenter.fr
    version: v1
- path: patches/logstash-patches.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: logstashes.logstash.k8s.webcenter.fr
    version: v1
