name: "build"

on:
  push:
    branches:
      - main
      - v1alpha1
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - v1alpha1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dagger
        uses: dagger/dagger-for-github@v7
        with:
          version: 0.14.0
          call: ci --ci --version ${VERSION} --registry-username env:REGISTRY_USERNAME --registry-password env:REGISTRY_PASSWORD --git-token env:GITHUB_TOKEN ${IS_TAG}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.event_name == 'pull_request' && 'pr.' +  github.run_number || 'rc.' +  github.run_number }}
          IS_TAG: ${{ github.ref_type == 'tag' && '--is-tag' || '' }}